all:
  children:

    rocky_servers:
      hosts:
        vml-oVirt-rocky.lab.local:
        vml-kvm01-rocky.lab.local:
        vml-kvm02-rocky.lab.local:

    debian_servers:
      hosts:
        vml-openstack-ubuntu.lab.local:
