apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-ontap-nas-advanced
type: Opaque
stringData:
  username: trident
  password: Geheim123!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-ontap-nas
spec:
  version: 1
  storageDriverName: ontap-nas
  managementLIF: 172.28.17.35
  dataLIF: 192.168.11.35
  backendName: ontap-nas
  autoExportCIDRs:
  - 192.168.11.0/24
  autoExportPolicy: true
  credentials:
    name: backend-tbc-ontap-nas-advanced
  storagePrefix: trident
  nfsMountOptions: nfsvers=3
  defaults:
    snapshotPolicy: default-1weekly
    snapshotReserve: '10'
    spaceReserve: volume
    exportPolicy: myk8scluster
    snapshotReserve: '10'
  deletionPolicy: retain

