- name: Install SSH server
  package:
    name: openssh-server
    state: present

- name: Enable SSH
  service:
    name: "{{ 'sshd' if ansible_os_family == 'RedHat' else 'ssh' }}"
    enabled: true
    state: started
