---
- name: Debian Initial Configuration
  hosts: debian_servers
  become: true

  roles:
    - repositories
    - base_packages
    - hostname
    - timezone
    - ssh
    - firewalld
    - networkmanager
    - monitoring_tools
    - admin_tools
    - cockpit
    - snap
    - vm_guest_tools
    - { role: gui_workstation, when: install_gui }
